### PR TITLE
replace deprecated call Seq.nth with Seq.item

### PR DESCRIPTION
**Pull request by vilinski**

### CODE REVIEW

**Comment by vilinski** [comment]
ok, was just a try... fix was simple, but hides some more. Don't know how to fix this or test
- AppVeyor can't find unit.framework.dll, 
- Travice CI uses MONO 3.2.5, mine is Stable 4.2.1.102

**Comment by mavnn** [comment]
Hi @vilinski . The tests not running correctly on AppVeyor is related to the breaking changes introduced in NUnit v3. I'll try and clear up the repository soon to use paket to avoid some of these issues!

About your change, we can't (unfortunately) just change the method used, as this will break libraries being compiled with older versions of the F# compiler which I'd prefer to avoid (and is being shown on Travis). We probably need to include a suitable #if statement or start separating different versions of the files for different versions of the compiler.

**Comment by mavnn** [comment]
I've updated the build scripts to use a compatible version of NUnit again, and as you can see things now build on appveyor.

I've added a matrix for both versions 3.2.8 and latest of mono in master, to see if we can find a suitable set of compiler directives to both remove the warning and still be buildable with older versions of the F#.

**Comment by dsyme** [comment]
I've address this in #78 through rewriting that particular bit of code, I'll close this

**Pull request closed without merging**
