### PR TITLE
Make Type Providers work with Mono 5.0+ Fixes https://github.com/fsha…

### PR DESCRIPTION
**Pull request by nosami**
…rp/fsharp/issues/738

### CODE REVIEW

**Comment by mavnn** [comment]
It's a pity Travis doesn't have mono 5 yet.

**Comment by sergey-tihon** [comment]
mono 5 is not released yet, but available on Travis in `beta`, `alpha` and `nightly` Mono channels

**Comment by nosami** [comment]
It's essentially the same fix as [this](https://github.com/fsharp/fsharp/pull/687/files)

**Comment by sergey-tihon** [comment]
Close this PR in favor of #120 
Thank you @nosami

**Pull request closed without merging**
