### PR TITLE
Allow arrays of provided types

### PR DESCRIPTION
**Pull request by skovlund**
http://stackoverflow.com/questions/24065723/how-do-i-create-type-for-array-of-providedtype

### CODE REVIEW

**Comment by mavnn** [comment]
Hi @skovlund !
Thanks for this, unfortunately the merged results don't seem to be building at the moment. You should be able to view the build logs here: https://ci.appveyor.com/project/mavnn/fsharp-typeproviders-starterpack/build/74

If you don't get a chance to look at this I'll try and fix it up over the next fews days.

**Comment by mavnn** [comment]
I don't have time to fully investigate right now, but I think the fix might be as simple as changing line 1133 from:

    override __.UnderlyingSystemType =

to 

    override this.UnderlyingSystemType =

Feel free to send an update commit and let the test builds run.

**Comment by skovlund** [comment]
Hi, I reverted the last commit, and it should work now. At least the test builds don't fail.

**Comment by mavnn** [comment]
Thanks!

**Pull request merged**
