### PR TITLE
Add way to restrict assembly names in mapping

### PR DESCRIPTION
**Pull request by tpetricek**
This makes it possible to fix funny bug in F# Data/FsLab.

When replacing one type form `FSharp.Core.DesignTime.dll`, the original code was picking a type from `Deedle.dll` (which inlines CSV parser and contains type with the same name, but not with all the functions). This is just because Deedle appeared earlier in the list of referenced assemblies.

With this fix in, we can create the replacer using:

    let bindingContext = 
       ProvidedTypesContext.Create(cfg, 
           [ "FSharp.Data.DesignTime", "FSharp.Data" ])

This way, types from `FSharp.Data.DesignTime` will only be mapped to types from assembly with a name starting with `FSharp.Data`. If no `assemblyReplacementMap` is specified, it behaves as before and picks type from first assembly that contains it.

/cc @dsyme - I'm merging this to fix F# Data bug, but post-merge review would be appreciated!

### CODE REVIEW

**Comment by tpetricek** [comment]
(Also, I guess merging #920 as part of the next release makes sense.)

**Comment by ovatsus** [comment]
This broke backward compatibility, the new param should be optional

**Comment by tpetricek** [comment]
Hmm, I thought the only entry point for this is `ProvidedTypesContext.Create` (and I made it optional there). Should people use the `AssemblyReplacer` constructor directly too?

**Comment by ovatsus** [comment]
We use the ProvidedTypesContext constructor directly on FSharp.Data. Remember that everything that's internal here is actually public, given the way the starter pack is included via files directly with paket

**Comment by tpetricek** [comment]
Yeah, I must have missed that - I was probably building just the normal net40 version when testing it. Sorry about the troubles & thanks for figuring this out!

**Comment by ovatsus** [comment]
no worries

**Pull request merged**
