### PR TITLE
Build process update

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
Now I have no idea what it wrong with latest FAKE/FCS ...

**Comment by mavnn** [comment]
It doesn't look that connected to your changes. Mono 4.8 was giving similar errors for @nosami yesterday.

**Comment by sergey-tihon** [comment]
I just want to prepare this repo for Mono 5, because seems that [Mono 5.0.0.100 is released](https://developer.xamarin.com/releases/current/) yesterday and will be in `latest` Mono channel soon... and `FAKE 4.6.1` is the first version that could compile `build.fsx` on `Mono 5`

**Comment by sergey-tihon** [comment]
Sorry, but I probably I need to ask help of experts // @forki @dsyme 
Because without fixing this build and merging #118 we could not rerelease Mono5 compatible versions of F# type providers ... So all `VS for Mac` users and those who install new Mono manually will not be able to use TPs

**Comment by sergey-tihon** [comment]
this is interesting ...

**Comment by dsyme** [comment]
@sergey-tihon I'm trying to update this now.  I had to disable some of the "examples" tests though

**Comment by dsyme** [comment]
@sergey-tihon Fixed the basic problems by updating FAKE, but had to disable some tests.  

Also there are additional reflection emit tests failing on Mono latest, and even Mono 4.8.1 seems to have problems

**Comment by dsyme** [comment]
@sergey-tihon I'll get it green by disabling tests and adding issues to track them

**Comment by sergey-tihon** [comment]
Thank you @dsyme. I see that PCL tests failing on Mono 5+
Do we go to fix them at all or Mono 5+ in the new land for .net standard providers?

**Comment by sergey-tihon** [comment]
@dsyme The issue here is that this code
https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/blob/master/src/ProvidedTypesTesting.fs#L597-L617
generates an incorrect path to `FSharp.Core.dll` on Mono 5+

**Example**:
``/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/Reference Assemblies/Microsoft/FSharp/.NETCore/3.259.3.1/FSharp.Core.dll`` and there is no such folder as ``/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/Reference Assemblies/`` in Mono 5.2.0

I did found some subset of used libraries here `/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/fsharp/api` but I am not sure that is it right location. Could you please guide me into the right direction? What is the right location for all `FSharp.Core.dll` libs on Mono 5+

The content of ``/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/fsharp/api``
```
.
./.NETCore
./.NETCore/3.259.41.0
./.NETCore/3.259.41.0/FSharp.Core.dll
./.NETCore/3.259.41.0/FSharp.Core.optdata
./.NETCore/3.259.41.0/FSharp.Core.sigdata
./.NETCore/3.259.41.0/FSharp.Core.xml
./.NETCore/3.7.41.0
./.NETCore/3.7.41.0/FSharp.Core.dll
./.NETCore/3.7.41.0/FSharp.Core.optdata
./.NETCore/3.7.41.0/FSharp.Core.sigdata
./.NETCore/3.7.41.0/FSharp.Core.xml
./.NETCore/3.78.41.0
./.NETCore/3.78.41.0/FSharp.Core.dll
./.NETCore/3.78.41.0/FSharp.Core.optdata
./.NETCore/3.78.41.0/FSharp.Core.sigdata
./.NETCore/3.78.41.0/FSharp.Core.xml
./.NETFramework
./.NETFramework/v4.0
./.NETFramework/v4.0/4.3.0.0
./.NETFramework/v4.0/4.3.0.0/FSharp.Core.dll
./.NETFramework/v4.0/4.3.0.0/FSharp.Core.optdata
./.NETFramework/v4.0/4.3.0.0/FSharp.Core.sigdata
./.NETFramework/v4.0/4.3.0.0/FSharp.Core.xml
./.NETFramework/v4.0/4.3.1.0
./.NETFramework/v4.0/4.3.1.0/FSharp.Core.dll
./.NETFramework/v4.0/4.3.1.0/FSharp.Core.optdata
./.NETFramework/v4.0/4.3.1.0/FSharp.Core.sigdata
./.NETFramework/v4.0/4.3.1.0/FSharp.Core.xml
./.NETFramework/v4.0/4.4.0.0
./.NETFramework/v4.0/4.4.0.0/FSharp.Core.dll
./.NETFramework/v4.0/4.4.0.0/FSharp.Core.optdata
./.NETFramework/v4.0/4.4.0.0/FSharp.Core.sigdata
./.NETFramework/v4.0/4.4.0.0/FSharp.Core.xml
./.NETFramework/v4.0/4.4.1.0
./.NETFramework/v4.0/4.4.1.0/FSharp.Core.dll
./.NETFramework/v4.0/4.4.1.0/FSharp.Core.optdata
./.NETFramework/v4.0/4.4.1.0/FSharp.Core.sigdata
./.NETFramework/v4.0/4.4.1.0/FSharp.Core.xml
./.NETPortable
./.NETPortable/3.47.41.0
./.NETPortable/3.47.41.0/FSharp.Core.dll
./.NETPortable/3.47.41.0/FSharp.Core.optdata
./.NETPortable/3.47.41.0/FSharp.Core.sigdata
./.NETPortable/3.47.41.0/FSharp.Core.xml
```

**Comment by sergey-tihon** [comment]
This PR is ready to be merged.

@mavnn may I ask for permissions to publish NuGet package?
So I can:
- merge all open PRs
- Fix parameter names in fsi file #127 
- release the latest version on NuGet #126

**Comment by mavnn** [comment]
Sergey, I've not had time to look at this in far too long! Absolutely feel
free to update nuget - I think it will happen automatically via CI once the
build is fixed, but if not ping me and all give you access on nuget.org.

**Comment by sergey-tihon** [comment]
@mavnn both builds are green, but no new NuGet package published =(

**Comment by mavnn** [comment]
Will make sure one goes out today 👍

**Pull request merged**
