### PR TITLE
Migration to NUnit3

### PR DESCRIPTION
**Pull request by sergey-tihon**

### CODE REVIEW

**Comment by sergey-tihon** [comment]
@forki One thing is strange in migration to `NUnit3` - I need to do
```fsharp
open Fake.Testing.NUnit3
```

**Comment by forki** [comment]
I thought we autoopen that one

**Comment by sergey-tihon** [comment]
I guess `[<AutoOpen>]` open module `NUnit3` inside its namespace `Fake.Testing` only.
So `open Fake.Testing` also works

**Comment by sergey-tihon** [comment]
Maybe it is ok... but not really obvious.

**Pull request merged**
